version: '3'
services:
  node-app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - my-network
    environment:
      - PORT=8000
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - mongo-db:/data/db


volumes:
  mongo-db:

networks:
  my-network:
    external: true