version: '3'
services:
  node-app:
    build: .
    networks:
      - my-network
    environment:
      - PORT=8000
    depends_on:
      - mongo

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
    networks:
      - my-network

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yashasavee
      - MONGO_INITDB_ROOT_PASSWORD=yaash2522
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    networks:
      - my-network


volumes:
  mongo-db:

networks:
  my-network:
    external: true